
### 1. Регистрация пользователя (Register)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "sultan-test7@example.com",
  "password": "1234567"
}


### 2. Логин пользователя (Login)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "sultan-test7@example.com",
  "password": "1234567"
}


### 2 Token/profile
GET http://localhost:3000/auth/myProfile
Content-Type: application/json
Authorization: Bearer 



### Create todo
POST http://localhost:3000/auth/todos
Content-Type: application/json
Authorization: Bearer 
{
  "title": "bla bla bla"
}


### Delete todo
DELETE http://localhost:3000/auth/todos/{Тут ID}
Authorization: Bearer 
